
#define FPS			60
#define MAX_PIXELS_PER_SCANLINE	240
#define MAX_SCANLINES		135
#define PIXELS			(MAX_PIXELS_PER_SCANLINE*MAX_SCANLINES)

#define VRAM_SIZE		0x20000
#define VRAM_SIZE_MASK		(VRAM_SIZE-1)
